### PR TITLE
Do not allow setting the type-export-policy to :all, it breaks compilation currently

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by doudou** [comment]
I would rather NOT merge this back into master.

**Comment by goldhoorn** [comment]
I would like to merge this in master because otherwise the OCL build does not work, Including buildserver and homepage generation.

The issue on orogen is available, so far this is a valid workaround. (https://github.com/orocos-toolchain/orogen/issues/50).

As soon the issue is solved, this commit can be reverted.

**Comment by goldhoorn** [comment]
@doudou either this or

https://github.com/rock-core/package_set/pull/54

or the issue should be merged/fixed we cannot generate a homepage otherwiese
the current HP does not include all packages it's only a minimal build)

**Comment by doudou** [comment]
rock-core/package_set#54 has been merged, can we close this ?

**Comment by goldhoorn** [comment]
The problem with base types still apply.
I would prefer to merged this and revert this when get merged  the oroge bug get fixed.

**Comment by doudou** [comment]
Fair enough ...

**Pull request merged**
